### ISSUE TITLE
Integrate GGHL into MMRotate. 

### ISSUE THREAD

**Issue by yangxue0827** [Shank2358/GGHL#10]
Nice work！Would you be interested in integrating GGHL into our MMRotate?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Shank2358** [comment]
> 

Hi, 

> MMRotate

Hi, Thank you for your valuable comments on our paper. I have followed the release of MMRotate recently and I am learning it 😸. It's an awesome job 🤩🤩. Of course, I have plans to implement GGHL on the MMRotate framework in the future. 
Thank you.

**Comment by yangxue0827** [comment]
Thank you for your attention. Can you send your WeChat to my email, so that we can communicate further. My email is yangxue-2019-sjtu@sjtu.edu.cn

**Comment by Shank2358** [comment]
> Thank you for your attention. Can you send your WeChat to my email, so that we can communicate further. My email is [yangxue-2019-sjtu@sjtu.edu.cn](mailto:yangxue-2019-sjtu@sjtu.edu.cn)

I have sent you an email, please check it. Thank you.

**Comment by yangxue0827** [comment]
Sorry, I didn't receive any mail yet include my spam mailbox . Did you send to the correct address? Can you resend it, or send it to another email: yangxue0827@126.com

**Comment by Shank2358** [comment]
> yangxue-2019-sjtu@sjtu.edu.cn

Sorry, I've resend it.

**Comment by yangxue0827** [comment]
Got it.
