### ISSUE TITLE
作者你好，请问你的特征图可视化使用什么工具做的呢

### ISSUE THREAD

**Issue by lalalagogogochong** [Shank2358/GGHL#11]
![image](https://user-images.githubusercontent.com/44855506/160228232-4b3208d5-878c-4190-b9ae-2583c95f6a09.png)

**Comment by Shank2358** [comment]
> ![image](https://user-images.githubusercontent.com/44855506/160228232-4b3208d5-878c-4190-b9ae-2583c95f6a09.png)

就是拿matplotlib画的呀~~

**Comment by lalalagogogochong** [comment]
> matplotlib
谢谢你啦，想问一下，仓库中有这一部分的代码吗，想学习一下

**Comment by Shank2358** [comment]
> > matplotlib
> > 谢谢你啦，想问一下，仓库中有这一部分的代码吗，想学习一下

仓库里面木有，我重新更新了一下，画图那个是datasets_show.py，直接运行这个文件就行，你可以更新一下康康
代码长下面这样，就很简单
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
img = np.uint8(np.transpose(img, (1, 2, 0)) * 255) ##把图像转换成unint8的array
mask_s = np.max(label_sbbox[:, :, 16:], -1, keepdims=True) 
##label_sbbox就是分配到s那一层（总共三层s,m,l）的label, [:, :, 16:]16以后是每一类别的分配，取最大值
plt.figure("mask_s")  ##图像窗口名称
plt.imshow(mask_s, cmap='jet', vmax=1, vmin=0) ##画图
cb = plt.colorbar() ##添加右边那条colorbar
tick_locator = ticker.MaxNLocator(nbins=5) ##colorbar的间隔
cb.locator = tick_locator
cb.update_ticks()

**Comment by lalalagogogochong** [comment]
> 仓库里面木有，我重新更新了一下，画图那个是datasets_show.py，直接运行这个文件就行，你可以更新一下康康
> 代码长下面这样，就很简单

好嘞，太感谢你了

**Comment by Shank2358** [comment]
> > 仓库里面木有，我重新更新了一下，画图那个是datasets_show.py，直接运行这个文件就行，你可以更新一下康康
> > 代码长下面这样，就很简单
> 
> 好嘞，太感谢你了

不客气，就是那个文件里我注释掉的那几行，打开就行。我没有封装，你可以把那些重新封装一个可视化工具。上传完了~~~
