### ISSUE TITLE
Error when trying to execute demo on single image 

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/GGHL#19]
![image](https://user-images.githubusercontent.com/37477283/182116923-d7ce00c8-3752-44e0-a7b6-5abf7b9bde2d.png)

**Comment by Crescent-Ao** [comment]
Can you provide more information about inference settings such as config, log information, input image?

**Comment by TerrafYassin** [comment]
config :
# coding=utf-8
DATA_PATH = "/content/drive/MyDrive/HRSC2016"#"F:/Datasets/DOTAx/test/"#
PROJECT_PATH = "/content/drive/MyDrive/GGHL/"

DATA = {"CLASSES": [
                  'ship',
                   ],

        "NUM": 1}

DATASET_NAME = "train_HRSC2016"
MODEL = {"STRIDES":[8, 16, 32]}

MAX_LABEL = 1000
SHOW_HEATMAP = False
SCALE_FACTOR = 2.0#2.0
SCALE_FACTOR_A = 2.0 #3.0

TRAIN = {
    "EVAL_TYPE": 'VOC',  # ['VOC', 'COCO']
    "TRAIN_IMG_SIZE": 800,
    "TRAIN_IMG_NUM": 63182,
    "AUGMENT": True,
    "MULTI_SCALE_TRAIN": True,
    "MULTI_TRAIN_RANGE": [23, 28, 1],
    "BATCH_SIZE": 8,
    "IOU_THRESHOLD_LOSS": 0.6,
    "EPOCHS": 151,
    "NUMBER_WORKERS": 12,
    "MOMENTUM": 0.9,
    "WEIGHT_DECAY": 0.0005,
    "LR_INIT": 1e-4,
    "LR_END": 1e-6,
    "WARMUP_EPOCHS": 5,
    "IOU_TYPE": 'GIOU'  # ['GIOU','CIOU']
}

TEST = {
    "EVAL_TYPE": 'VOC',
    "EVAL_JSON": 'test.json',
    "EVAL_NAME": 'test',
    "NUM_VIS_IMG": 0,
    "TEST_IMG_SIZE": 800,
    "BATCH_SIZE": 4,
    "NUMBER_WORKERS": 24,
    "CONF_THRESH": 0.3,
    "NMS_THRESH": 0.45,
    "IOU_THRESHOLD": 0.5,
    "NMS_METHODS": 'NMS',
    "MULTI_SCALE_TEST": False,
    "MULTI_TEST_RANGE": [736, 864, 96],
    "FLIP_TEST": False
}

**Comment by TerrafYassin** [comment]
for the input images i select some images from test folder of HRSC2016 dataset

**Comment by TerrafYassin** [comment]
![image](https://user-images.githubusercontent.com/37477283/182327493-45a6b1d3-0c88-4d4d-929e-f6ed91b35649.png)

**Comment by Shank2358** [comment]
> ![image](https://user-images.githubusercontent.com/37477283/182116923-d7ce00c8-3752-44e0-a7b6-5abf7b9bde2d.png)

I have updated the codes to fix this problem. Please update the codes. Thanks.

**Comment by YoonaIAN** [comment]
请问这个代码是在pytorch框架下的吗

**Comment by Crescent-Ao** [comment]
Sure, the network is implemented on the Pytorch.

**Comment by YoonaIAN** [comment]
> Sure, the network is implemented on the Pytorch.

谢谢。再请问一下，如果想用您训练好的权重测试图片是不是只要把环境配置好，然后在config.py修改好路径，运行test.py就可以了？
