### ISSUE TITLE
Show heatmap after using attention module

### ISSUE THREAD

**Issue by terrafya** [Shank2358/GGHL#20]
Hi , 
please i want to show heatmap after using NP attention  module as mentionned in your paper ( bellow ) , how can i do it 
![image](https://user-images.githubusercontent.com/110535404/183622616-aaeb5cd3-b82f-4682-9641-d7fb2ce734bf.png)

**Comment by Shank2358** [comment]
> Hi , please i want to show heatmap after using NP attention module as mentionned in your paper ( bellow ) , how can i do it ![image](https://user-images.githubusercontent.com/110535404/183622616-aaeb5cd3-b82f-4682-9641-d7fb2ce734bf.png)

I answered this question here.
https://github.com/Shank2358/NPMMR-Det/issues/19
