### ISSUE TITLE
大佬能公开一下制作标签的代码吗

### ISSUE THREAD

**Issue by Marm7** [Shank2358/GGHL#3]
感谢！！！

**Comment by Shank2358** [comment]
> 感谢！！！

    已经更新了（在datasets_tools的文件夹中有一个DOTA2Train.py的文件），试试看能不能用。
    首先，需要使用DOTA数据集的官方工具 [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit) 进行图像和标签裁剪。然后运行DOTA2Train.py将它们转换为GGHL所需的格式。DOTA_devkit的使用可以看官方仓库的教程，如果还有问题也可以问我。谢谢。

    I have updated it. There is a DOTA2Train.py file in the datasets_tools folder that can be used to generate training and test format labels.
    First, you need to use [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit) , the official tools of the DOTA dataset, for image and label splitting. Then, run DOTA2Train.py to convert them to the format required by GGHL. 
    For the use of DOTA_devkit, please refer to the tutorial in the official repository. If you have any questions, you can also ask me. 
    Good luck. Thank you.

**Comment by Shank2358** [comment]
> 感谢！！！

你好。标签转换的代码对于除了论文里那些数据集以外的其他数据集可能有一些bug（主要是顶点顺序的问题，详见ISSUES # 1），我重新做了修复了。请更新一下代码，谢谢。

**Comment by Marm7** [comment]
> 

多谢提醒
今天读了你NPMMR文章，fig.3的Sobel0九宫格右下角的1可能和代码里不太一样

**Comment by Shank2358** [comment]
> > 
> 
> 多谢提醒 今天读了你NPMMR文章，fig.3的Sobel0九宫格右下角的1可能和代码里不太一样

不客气，大家还反馈了一些bug最近，我还会持续更新这个仓库。
NPMMR那个是文章里的图画错了，那个1是-1.。。。。。就是sobel水平方向的，出错了十分抱歉啊
