### ISSUE TITLE
训练loss问题

### ISSUE THREAD

**Issue by lalalagogogochong** [Shank2358/GGHL#5]
请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么
![image](https://user-images.githubusercontent.com/44855506/147712614-febe123c-674d-49de-bdda-f67911f2ae4a.png)

**Comment by Shank2358** [comment]
> 请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 ![image](https://user-images.githubusercontent.com/44855506/147712614-febe123c-674d-49de-bdda-f67911f2ae4a.png)

loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右（cosin衰减策略情况下）。比如这是我训练DOTA数据集的loss情况。
![image](https://user-images.githubusercontent.com/33946139/147714274-a41bd4b6-aec6-4f03-aa67-79acb434b3cf.png)


另外，因为用了cosin衰减策略，所以前期学习率会偏大。调试的时候您也可以改为step策略去调参。

**Comment by lalalagogogochong** [comment]
> > 请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 ![image](https://user-images.githubusercontent.com/44855506/147712614-febe123c-674d-49de-bdda-f67911f2ae4a.png)
> 
> loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右。比如这是我训练DOTA数据集的loss情况。 ![image](https://user-images.githubusercontent.com/33946139/147714274-a41bd4b6-aec6-4f03-aa67-79acb434b3cf.png)

嗯嗯好的，我看一下，谢谢啦

**Comment by lalalagogogochong** [comment]
> > > 请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 ![image](https://user-images.githubusercontent.com/44855506/147712614-febe123c-674d-49de-bdda-f67911f2ae4a.png)
> > 
> > 
> > loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右。比如这是我训练DOTA数据集的loss情况。 ![image](https://user-images.githubusercontent.com/33946139/147714274-a41bd4b6-aec6-4f03-aa67-79acb434b3cf.png)
> 
> 嗯嗯好的，我看一下，谢谢啦

您好，还有个问题请教一下，这个test.txt里面的图片名称包含图片的路径吗，还有就是下面的00001,00002这个是什么呢，没有文件格式，是图片吗
![image](https://user-images.githubusercontent.com/44855506/147796485-095a8cb1-10fc-4e81-8625-411511fb5225.png)

**Comment by Shank2358** [comment]
test.txt里面的图片名称不包含路径和后缀，只是单纯的图片名，我的图片名是00001，00002这样的，您可以改成自己的，就是标准的VOC格式。
谢谢


发件人: lalalagogogo
发送时间: 2021年12月31日 8:37
收件人: Shank2358/GGHL
抄送: Zhanchao Huang; Comment
主题: Re: [Shank2358/GGHL] 训练loss问题 (Issue #5)

请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 
loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右。比如这是我训练DOTA数据集的loss情况。 
嗯嗯好的，我看一下，谢谢啦
您好，还有个问题请教一下，这个test.txt里面的图片名称包含图片的路径吗，还有就是下面的00001,00002这个是什么呢，没有文件格式，是图片吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lalalagogogochong** [comment]
> test.txt里面的图片名称不包含路径和后缀，只是单纯的图片名，我的图片名是00001，00002这样的，您可以改成自己的，就是标准的VOC格式。 谢谢 发件人: lalalagogogo 发送时间: 2021年12月31日 8:37 收件人: Shank2358/GGHL 抄送: Zhanchao Huang; Comment 主题: Re: [Shank2358/GGHL] 训练loss问题 (Issue #5) 请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右。比如这是我训练DOTA数据集的loss情况。 嗯嗯好的，我看一下，谢谢啦 您好，还有个问题请教一下，这个test.txt里面的图片名称包含图片的路径吗，还有就是下面的00001,00002这个是什么呢，没有文件格式，是图片吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

好的，谢谢您，又有个新问题，这个推理速度是正常的吗，是我哪里设置有问题吗，速度有点慢，再就是可视化的结果是评估完再生成图片吗， 为什么我这边没有可视化结果呢
![image](https://user-images.githubusercontent.com/44855506/147801797-bfbc290a-a6e5-49e6-868d-5dd707d13f6e.png)

**Comment by Shank2358** [comment]
> > test.txt里面的图片名称不包含路径和后缀，只是单纯的图片名，我的图片名是00001，00002这样的，您可以改成自己的，就是标准的VOC格式。 谢谢 发件人: lalalagogogo 发送时间: 2021年12月31日 8:37 收件人: Shank2358/GGHL 抄送: Zhanchao Huang; Comment 主题: Re: [Shank2358/GGHL] 训练loss问题 (Issue #5) 请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右。比如这是我训练DOTA数据集的loss情况。 嗯嗯好的，我看一下，谢谢啦 您好，还有个问题请教一下，这个test.txt里面的图片名称包含图片的路径吗，还有就是下面的00001,00002这个是什么呢，没有文件格式，是图片吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 好的，谢谢您，又有个新问题，这个推理速度是正常的吗，是我哪里设置有问题吗，速度有点慢，再就是可视化的结果是评估完再生成图片吗， 为什么我这边没有可视化结果呢 ![image](https://user-images.githubusercontent.com/44855506/147801797-bfbc290a-a6e5-49e6-868d-5dd707d13f6e.png)

这个推理速度是正常的慢版本的，主要是慢在NMS那里（就是纯python版本的旋转框NMS，用的shapely库），这是因为考虑到很多人编译加速版可能出现问题所以给了单纯python版本的，当目标很多（也就是要做很多NMS的时候）会很慢。
![image](https://user-images.githubusercontent.com/33946139/147806851-5f3502ed-20b0-4ef4-9133-19a783624eae.png)
加速版的在.//datasets_tools/DOTA_devkit里面有一个c版本的nms，是DOTA官方给出的，你可以换成那个。

用法是首先编译DOTA_devkit工具包和里面的polyiou函数，
![image](https://user-images.githubusercontent.com/33946139/147807038-7055d9de-c471-4b61-a7ce-f48e0f089ac1.png)
然后把原版NMS上面那句注释掉不用，全部推理完成按类别保存到./predictionR/voc后，调用./DOTA_devkit/ResultMerge_multi_process.py进行后处理。这是DOTA版本的，把拼接回大图和NMS都用了，如果你自己的数据集可以直接使用这个代码的前半段polynms，
![image](https://user-images.githubusercontent.com/33946139/147807213-635b0243-97bb-4bfc-9b4f-b0a5c678bca5.png)

我这两天重新写一版把这个嵌入原来代码里面的，稍后更新。
谢谢。

**Comment by Shank2358** [comment]
> > test.txt里面的图片名称不包含路径和后缀，只是单纯的图片名，我的图片名是00001，00002这样的，您可以改成自己的，就是标准的VOC格式。 谢谢 发件人: lalalagogogo 发送时间: 2021年12月31日 8:37 收件人: Shank2358/GGHL 抄送: Zhanchao Huang; Comment 主题: Re: [Shank2358/GGHL] 训练loss问题 (Issue #5) 请问一下，训练过程中loss一般为多少呢，我训练了40个epoch，loss目前还在16.8左右，这个是正常的么 loss的值和训练数据集还有训练超参数（batch_size,learning rate等）有关，不同情况不一样的。训练时在./log文件夹中会自动保存训练日志，您可以用tensorboard将loss的曲线画出来看看收敛的情况，如果收敛的比较好了就可以停止训练了。您这边仅从数值上看似乎已经收敛了，epoch=80似乎有点多。DOTAv1.0数据集用预训练权重通常我是训练36个epoch左右。比如这是我训练DOTA数据集的loss情况。 嗯嗯好的，我看一下，谢谢啦 您好，还有个问题请教一下，这个test.txt里面的图片名称包含图片的路径吗，还有就是下面的00001,00002这个是什么呢，没有文件格式，是图片吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 好的，谢谢您，又有个新问题，这个推理速度是正常的吗，是我哪里设置有问题吗，速度有点慢，再就是可视化的结果是评估完再生成图片吗， 为什么我这边没有可视化结果呢 ![image](https://user-images.githubusercontent.com/44855506/147801797-bfbc290a-a6e5-49e6-868d-5dd707d13f6e.png)

您好，NMS的代码已经更新，麻烦更新一下。新的eval代码是evaluatorGGHL_new.py，这版本使用了上午说的NMS_fast，使用前需要编译一下./DOTA_devkit即可，可以直接在test.py里面使用了，无需上午说的那样分开用了。实测了一下，速度快了很多。如果还有问题可以随时和我反馈。
