### ISSUE TITLE
is there any demo script to test a single image？

### ISSUE THREAD

**Issue by LLsmile** [Shank2358/GGHL#6]
Is there any demo script to test a single image？I want to test a single image to check the performance on my datasets.

**Comment by Shank2358** [comment]
> Is there any demo script to test a single image？I want to test a single image to check the performance on my datasets.

目前没有写单张图的Demo，可以用test.py，把测试数据集的图像改成单张的就行了。我一会儿写个单张的脚本吧，这几天会更新。

**Comment by LLsmile** [comment]
Thanks.

**Comment by Shank2358** [comment]
> Thanks.

Hi, I have updated the demo of the single image test (demo.py and evaluator_demo.py). You only need to modify the image path when using it. Thanks. 
最近寒假有点懒，更新慢了，抱歉。
