### ISSUE TITLE
FCOS + GGHL中OLA模块代码复现问题

### ISSUE THREAD

**Issue by zhuyh1223** [Shank2358/GGHL#8]
作者您好!感谢您分享非常棒的一项工作。

论文中FCOS + GGHL代码细节描述不是特别清楚，想向您确认一下OLA模块的复现细节。

FCOS + GGHL OLA模块的代码是对应dataloadR/datasets_FCOS_R.py文件吗？我看到其中正负点的采样不是采用论文中描述的计算二维高斯概率值的方式，而是根据计算的centerness的值进行采样。想请教一下您这样选择的依据是什么呢？这两种采样方式对不同检测方法的适配度会有较大差别吗？

**Comment by Shank2358** [comment]
> 作者您好!感谢您分享非常棒的一项工作。
> 
> 论文中FCOS + GGHL代码细节描述不是特别清楚，想向您确认一下OLA模块的复现细节。
> 
> FCOS + GGHL OLA模块的代码是对应dataloadR/datasets_FCOS_R.py文件吗？我看到其中正负点的采样不是采用论文中描述的计算二维高斯概率值的方式，而是根据计算的centerness的值进行采样。想请教一下您这样选择的依据是什么呢？这两种采样方式对不同检测方法的适配度会有较大差别吗？

您好啊，谢谢关注。
datasets_FCOS_R.py这个文件就是单纯的R-FCOS的分配方式，用的旋转的centerness，就是论文表格里面R-FCOS的baseline。

论文里FCOS+GGHL的是用的OLA的方式，就是datasets_obb.py这个，然后表征也用的论文的ORC，但是loss用的FCOS的loss，模型结构的head是retinanet那样的，（loss和head是和GGHL有区别，分配和OBB表征和GGHL一样，大概这样一个中间态的模型）。这些方法其实模块化之后主要就三部分：分配方式（在dataload里面）、模型结构、损失函数，对它们进行排列组合就可以得到论文里不同对比实验的模型啦。

两种采样方式还是有一些不一样的，在论文里面简单解释了一下，这里我再解释一下，如果您还有疑问我们也可以在这里继续讨论。
1）GGHL是直接根据坐标和公式可以算出每个像素点的PDF（就是论文OLA那些公式），但是现在许多其他论文里改的R-FCOS的R-Centerness方式，需要先计算HBB的centerness图然后再旋转。后者在逐网格点分配上可能面临插值的情况，因为centerness的heatmap旋转之后原来整数grid的值可能变换到非整数grid位置上，而GGHL没有这个问题，在datasets_FCOS_R.py代码里面就有对这样仿射变换的近似，您可以对比一下它和GGHL方式的代码就知道啦。
2）当两个目标重叠时候都分配问题，FCOS的centerness是分给面积更小的那个，GGHL的OLA是每个像素点比较并分给Gaussian PDF值大的那个，这里也不一样。因为比如DOTA数据集里面的港口和船，按centerness的方式可能大部分中间比较优质的像素点都分给船了，而某个在港口box中间区域的船，它的centerness边缘区域其实得分并不一定比港口centernesss得分高。还有其他很多类似的情况。
3）Centerness的分配可视化我在readme里面给了个图，
<img src="https://user-images.githubusercontent.com/33946139/147256008-467d03f4-876e-4065-99b6-02198a7d7d93.png" width="520">
可以看到像一个菱形，有四条很明显的“脊”和尖尖的角（这些视觉上看凸起来的位置得分比周围高，但实际上我们认为不一定是这样），而GGHL的高斯是一个平滑的椭圆（可以把里面想象成一圈一圈的小椭圆，每一圈椭圆圆周上的点的得分是一样的，我们觉得这样更合理，因为这些位置对于回归OBB的贡献本来就应该是相等的）。
4）当然，上面这些是通俗的描述，您也可以把高斯和centerness的公式写出来，求一下它们导数就知道它们的变化率和对应的变化情况，和前面那个解释是对应的。然后也可以用仿射变换公式算一下对FCOS的HBB的centerness进行旋转的情况，就能发现我刚才解释的插值问题，然后对旋转后的公式再求一下导数，就能对应（3）中的解释。
5）您也可以更直接的可视化出来看，就像我们readme里面那样，dataloadR里面不同分配策略的函数是都可以单独运行可视化出分配后的heatmap的，在issue #1里面有更多关于这个的解释。
6）论文因为篇幅的限制（已经在能塞的空间里塞得满满当当了），许多分析和解释很遗憾没能完全展示出来，非常抱歉。关于这些我都可以在这里给大家解释，非常欢迎讨论。

不知道这样解释是否容易理解？如果您还有疑问可以在这里留言，我们可以继续讨论。如果有解释不对的也欢迎批评指正。
谢谢。

**Comment by zhuyh1223** [comment]
感谢您详尽的解答！

我按照datasets_obb.py中的采样方法对FCOS的代码进行了更改。但是改进后在DOTA1.0数据集上的MAP为68.12%，比原版的68.79%略低一些。

改进的地方：1）原先版本将旋转框内的所有点作为正样本，改进的版本进一步选择二维高斯概率值高于阈值（0.05）的点为正样本；2）原先版本根据面积大小选择重叠的目标，改进的版本根据概率值大小选择重叠目标

其余地方与fcos原代码保持一致：1）采用p3-p7层（stride为[8, 16, 32, 64, 128]）；2）采用fcos表示方式与loss

更改的代码如下：
![image](https://user-images.githubusercontent.com/27856586/156561905-2f36f6f5-2d8e-4ef2-b5a5-b8e1879279c8.png)
![image](https://user-images.githubusercontent.com/27856586/156562128-62d0f1ce-88cc-4b6e-af67-524eac634387.png)

更改后版本的heatmap图和采样点可视化如下：
![P0007_0002](https://user-images.githubusercontent.com/27856586/156563972-baa4e762-00d1-48a1-b1f8-91c6ab29b9d6.png)
![P0007_0002_v0_cam](https://user-images.githubusercontent.com/27856586/156564143-62a1725c-86ba-493d-8600-326f6d199e85.png)

想问一下您有没有比较过仅更改fcos中的采样方式为OLA对结果的影响呢？也麻烦您看一下更改的代码是否有问题，可能是什么原因导致map值降低呢？

**Comment by Shank2358** [comment]
> 本的heatmap图和采样点

您好，谢谢您的反馈。

1）您代码关于高斯PDF的计算是和我的一样的，这个没有问题。
2）我正在试只对FCOS进行OLA分配的情况，有结果了会尽快和您反馈
3）看您分配的采样点和heatmap好像这个位置没有对上？是用了比如翻转这类数据增强吗还是？
![image](https://user-images.githubusercontent.com/33946139/156572327-ff2d7e11-ac94-4161-a36d-d926805d37ee.png)
4）采样点似乎有的偏离OBB了，请问这是label的可视化结果吗还是预测的结果可视化？我现在正在改我的代码，我把我的也画出来一下对比康康能不能找到原因。
![image](https://user-images.githubusercontent.com/33946139/156572558-14362b88-6bf7-4683-936f-651d48a63e50.png)
5）另外请问分层的策略是用的FCOS的[64,128,256,512,1024]这样的吗？还是OLA里面那个？分层似乎对结果也有影响，论文实验部分的表4里面有一些我的实验结果，我最近会再试试看FCOS那样分层的影响。
谢谢

**Comment by Shank2358** [comment]
> 感谢您详尽的解答！
> 
> 我按照datasets_obb.py中的采样方法对FCOS的代码进行了更改。但是改进后在DOTA1.0数据集上的MAP为68.12%，比原版的68.79%略低一些。
> 
> 改进的地方：1）原先版本将旋转框内的所有点作为正样本，改进的版本进一步选择二维高斯概率值高于阈值（0.05）的点为正样本；2）原先版本根据面积大小选择重叠的目标，改进的版本根据概率值大小选择重叠目标
> 
> 其余地方与fcos原代码保持一致：1）采用p3-p7层（stride为[8, 16, 32, 64, 128]）；2）采用fcos表示方式与loss
> 
> 更改的代码如下： ![image](https://user-images.githubusercontent.com/27856586/156561905-2f36f6f5-2d8e-4ef2-b5a5-b8e1879279c8.png) ![image](https://user-images.githubusercontent.com/27856586/156562128-62d0f1ce-88cc-4b6e-af67-524eac634387.png)
> 
> 更改后版本的heatmap图和采样点可视化如下： ![P0007_0002](https://user-images.githubusercontent.com/27856586/156563972-baa4e762-00d1-48a1-b1f8-91c6ab29b9d6.png) ![P0007_0002_v0_cam](https://user-images.githubusercontent.com/27856586/156564143-62a1725c-86ba-493d-8600-326f6d199e85.png)
> 
> 想问一下您有没有比较过仅更改fcos中的采样方式为OLA对结果的影响呢？也麻烦您看一下更改的代码是否有问题，可能是什么原因导致map值降低呢？

您好，谢谢您的反馈。

1）您代码关于高斯PDF的计算是和我的一样的，这个没有问题。
2）我正在试只对FCOS进行OLA分配的情况，有结果了会尽快和您反馈
3）看您分配的采样点和heatmap好像这个位置没有对上？是用了比如翻转这类数据增强吗还是？
![image](https://user-images.githubusercontent.com/33946139/156572327-ff2d7e11-ac94-4161-a36d-d926805d37ee.png)
4）采样点似乎有的偏离OBB了，请问这是label的可视化结果吗还是预测的结果可视化？我现在正在改我的代码，我把我的也画出来一下对比康康能不能找到原因。
![image](https://user-images.githubusercontent.com/33946139/156572558-14362b88-6bf7-4683-936f-651d48a63e50.png)
5）另外请问分层的策略是用的FCOS的[64,128,256,512,1024]这样的吗？还是OLA里面那个？分层似乎对结果也有影响，论文实验部分的表4里面有一些我的实验结果，我最近会再试试看FCOS那样分层的影响。
谢谢

**Comment by Shank2358** [comment]
> 感谢您详尽的解答！
> 
> 我按照datasets_obb.py中的采样方法对FCOS的代码进行了更改。但是改进后在DOTA1.0数据集上的MAP为68.12%，比原版的68.79%略低一些。
> 
> 改进的地方：1）原先版本将旋转框内的所有点作为正样本，改进的版本进一步选择二维高斯概率值高于阈值（0.05）的点为正样本；2）原先版本根据面积大小选择重叠的目标，改进的版本根据概率值大小选择重叠目标
> 
> 其余地方与fcos原代码保持一致：1）采用p3-p7层（stride为[8, 16, 32, 64, 128]）；2）采用fcos表示方式与loss
> 
> 更改的代码如下： ![image](https://user-images.githubusercontent.com/27856586/156561905-2f36f6f5-2d8e-4ef2-b5a5-b8e1879279c8.png) ![image](https://user-images.githubusercontent.com/27856586/156562128-62d0f1ce-88cc-4b6e-af67-524eac634387.png)
> 
> 更改后版本的heatmap图和采样点可视化如下： ![P0007_0002](https://user-images.githubusercontent.com/27856586/156563972-baa4e762-00d1-48a1-b1f8-91c6ab29b9d6.png) ![P0007_0002_v0_cam](https://user-images.githubusercontent.com/27856586/156564143-62a1725c-86ba-493d-8600-326f6d199e85.png)
> 
> 想问一下您有没有比较过仅更改fcos中的采样方式为OLA对结果的影响呢？也麻烦您看一下更改的代码是否有问题，可能是什么原因导致map值降低呢？

您好，我这边正在排查，会一点一点给您反馈。
1）首先，我找到了和您一样的图，用GGHL原版的分配代码，这些车辆是被分配到stride=16的层（GGHL只有三层），，以下是我可视化出来的结果。不知道您那边这些目标是被分配到哪一层的，我推测这个可能会是影响之一。
![image](https://user-images.githubusercontent.com/33946139/156591628-13244c65-3820-47d6-9135-8852808a23da.png)
2）我试了用FCOS的分层策略，也就是（64，128，256，512）这个，发现这张图上的目标被分配到了stride=16和stride=32的层（后者更多），可视化结果如下（我根据您的可视化结果也粗略地写了一个类似的），似乎这样的分层策略会有影响，初步印证了上述的推测。请问您是按照FCOS的策略进行分层的吗还是GGHL的？
![image](https://user-images.githubusercontent.com/33946139/156592866-efcff5c0-c02b-4f32-bf05-dd906998d533.png)
3）GGHL的分层策略和高斯半径是关联在一起的（就是那个IOU=0.3），也许会受到这个影响，我正在实验测试。另外这版代码里面的高斯半径取法是一个我偷懒的近似做法，完整做法是先计算完整个高斯椭圆，然后取半径0.7的区域，就是论文Algorithm1的做法。我原来在DOTA上测试两者性能差不多所以就用了这个（因为现在这个时间复杂度更低很多），我换回完整版试一下。然后我会再试一下调整分层策略和高斯半径有什么影响，似乎是这里和FCOS有差异。
对于FCOS的centerness策略，半径只和OBB有关系和分层阈值没有直接关系（只是分配到不同层大小的等比例变化），似乎不会受到这个的影响。
4）进一步地，根据上述推测，我还试着把直接目标全部分配到不同层，以下是分配到stride=4的层的结果，红色的小点点是采样点
![image](https://user-images.githubusercontent.com/33946139/156587712-48fc17b8-16fb-4a9c-8408-d32ccfebb57d.png)
然后以下是全部分配到stride=8的结果，也就是FCOS的P3，
![image](https://user-images.githubusercontent.com/33946139/156588331-f49ea101-fd69-454b-b62e-67761888a100.png)
以下是stride=16的结果，也就是FCOS的P4
![image](https://user-images.githubusercontent.com/33946139/156589334-f7d9ab31-3586-40c1-a460-8e5afd6bdae4.png)
再往下似乎不合适了，P5，P6，P7对于这些而言粒度太粗了。
5）刚才提到的，您可视化结果里右边那个车的heatmap似乎方向和OBB不一致，我这边代码可视化出来是一致的，不知道这个是不是影响结果的原因之一。您是否还有排查过其他图片，是否也有这样的情况？我这边排查了大约2k+的图像，都是对应一致的。
6）我想了一下，采样点画回原图有偏差是下采样后分配的原因，这个倒是一直都是FPN分层分配的问题。但是如果用FCOS的分层阈值似乎如（1）那样高斯被分配到stride更大的层，这种偏差会更大一些相比于分配到strid更小的层。这里我也没想太明白，原来也考虑过这种下采样偏差的情况，如有不对也请指正。
7）我准备修改代码试一下前面几种推测，还有单纯的FCOS和GGHL分配策略的影响，还需要一些时间。
8）写得有点乱...如果您有任何疑问都可以随时反馈，这个issue我做完一点就随时更新一点，像现在这样。
谢谢

**Comment by Shank2358** [comment]
> 感谢您详尽的解答！
> 
> 我按照datasets_obb.py中的采样方法对FCOS的代码进行了更改。但是改进后在DOTA1.0数据集上的MAP为68.12%，比原版的68.79%略低一些。
> 
> 改进的地方：1）原先版本将旋转框内的所有点作为正样本，改进的版本进一步选择二维高斯概率值高于阈值（0.05）的点为正样本；2）原先版本根据面积大小选择重叠的目标，改进的版本根据概率值大小选择重叠目标
> 
> 其余地方与fcos原代码保持一致：1）采用p3-p7层（stride为[8, 16, 32, 64, 128]）；2）采用fcos表示方式与loss
> 
> 更改的代码如下： ![image](https://user-images.githubusercontent.com/27856586/156561905-2f36f6f5-2d8e-4ef2-b5a5-b8e1879279c8.png) ![image](https://user-images.githubusercontent.com/27856586/156562128-62d0f1ce-88cc-4b6e-af67-524eac634387.png)
> 
> 更改后版本的heatmap图和采样点可视化如下： ![P0007_0002](https://user-images.githubusercontent.com/27856586/156563972-baa4e762-00d1-48a1-b1f8-91c6ab29b9d6.png) ![P0007_0002_v0_cam](https://user-images.githubusercontent.com/27856586/156564143-62a1725c-86ba-493d-8600-326f6d199e85.png)
> 
> 想问一下您有没有比较过仅更改fcos中的采样方式为OLA对结果的影响呢？也麻烦您看一下更改的代码是否有问题，可能是什么原因导致map值降低呢？

这里似乎也没对上，这个车车好像更往右边斜一点，就是左下-右上的方向，您的heatmap可视化是更偏左边斜一点的，左上-右下，这个好像不太明显看起来。您是否还有试过其他图，有没有类似的情况？还是说只是因为您的原图是做了数据增强之后的而heatmap是没有的所以看起来方向不一样。这个烦请您确认一下，因为您的代码截图了没有这部分我无法确认，似乎这个也会影响最终结果。谢谢。
![image](https://user-images.githubusercontent.com/33946139/156598166-439622fe-bb5b-4ac9-b10f-4190ddabb219.png)

**Comment by zhuyh1223** [comment]
感谢您这么快速的回复！

1）关于采样点图和heatmap图不对应的问题：我是直接在训练集上可视化的数据，会有随机翻转，所以两者没对应上。但是训练过程中图像和标签应该是一致的

2）采用的是和FCOS一致的stride=[8, 16, 32, 64, 128]的五层，层数分配策略是采用和FCOS一致的，即按照计算出来的[l, t, r, b] targets 范围分配不一样的层，所以同一个物体内不同的像素点可能会被分配到不同的层；我也试过像您代码里写的那样，按照物体的水平检测框长宽的大小分配不同层（这样同个物体的所有像素都分配到同样的层），但是这样跑出来的map是67.29%，比前者更低。代码如下，注释部分为后者：
![image](https://user-images.githubusercontent.com/27856586/156685827-b9ad3d34-5820-471b-a0a9-1c623ced6895.png)

3）我之前贴的结果是stride=8的，由于分辨率更高一点，所以可视化的时候就把所有物体都可视化P3层上了。实际上在实际分配的时候，是分配在stride=16, 和stride=32层上的，图像如下：
![P0007_0002_v1_cam](https://user-images.githubusercontent.com/27856586/156686300-96684b8e-b4f8-4c4e-b293-a2c894d97d47.png)
![P0007_0002_v2_cam](https://user-images.githubusercontent.com/27856586/156686871-0be4726b-e00f-46df-b099-f62a9a0cc833.png)

4) 我跑了一下datasets_FCOS_R.py中按照centerness分配方式的代码，得到的map为69.52%。看采样点图的话，可以看到按照高斯概率采样的点会较少一点，另两种方式会更多一点，会不会可能是由于前背景不均衡问题导致的？

**Comment by Shank2358** [comment]
> 

谢谢您的反馈。

1）和3）没问题啦，我明白了。

2）根据您的实验结果，stride=[8, 16, 32, 64, 128]的五层的时候，似乎按FCOS按采样点来分层比我们代码里按整个目标来分层效果更好，我刚把分层策略也改成这样，在我的代码上试一下康康效果。

4）高斯的采样点会更少一些因为只取了其中0.7半径范围的点，可以试试直接取bounding box内的整个高斯椭圆，这样点数应该会和centerness差不多。我们之前的实验中也发现高斯半径的范围和分层的参数tau对于结果影响挺大的。另外正如您所说，更少的采样点是有可能加重前背景不均衡的情况。

5）请问您使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels这样的吗，我对齐一下训练试试看。

谢谢。

**Comment by Shank2358** [comment]
> 感谢您这么快速的回复！
> 
> 1）关于采样点图和heatmap图不对应的问题：我是直接在训练集上可视化的数据，会有随机翻转，所以两者没对应上。但是训练过程中图像和标签应该是一致的
> 
> 2）采用的是和FCOS一致的stride=[8, 16, 32, 64, 128]的五层，层数分配策略是采用和FCOS一致的，即按照计算出来的[l, t, r, b] targets 范围分配不一样的层，所以同一个物体内不同的像素点可能会被分配到不同的层；我也试过像您代码里写的那样，按照物体的水平检测框长宽的大小分配不同层（这样同个物体的所有像素都分配到同样的层），但是这样跑出来的map是67.29%，比前者更低。代码如下，注释部分为后者： ![image](https://user-images.githubusercontent.com/27856586/156685827-b9ad3d34-5820-471b-a0a9-1c623ced6895.png)
> 
> 3）我之前贴的结果是stride=8的，由于分辨率更高一点，所以可视化的时候就把所有物体都可视化P3层上了。实际上在实际分配的时候，是分配在stride=16, 和stride=32层上的，图像如下： ![P0007_0002_v1_cam](https://user-images.githubusercontent.com/27856586/156686300-96684b8e-b4f8-4c4e-b293-a2c894d97d47.png) ![P0007_0002_v2_cam](https://user-images.githubusercontent.com/27856586/156686871-0be4726b-e00f-46df-b099-f62a9a0cc833.png)
> 
> 4. 我跑了一下datasets_FCOS_R.py中按照centerness分配方式的代码，得到的map为69.52%。看采样点图的话，可以看到按照高斯概率采样的点会较少一点，另两种方式会更多一点，会不会可能是由于前背景不均衡问题导致的？

谢谢您的反馈。

1）和3）没问题啦，我明白了。

2）根据您的实验结果，stride=[8, 16, 32, 64, 128]的五层的时候，似乎按FCOS按采样点来分层比我们代码里按整个目标来分层效果更好，我刚把分层策略也改成这样，在我的代码上试一下康康效果。

4）高斯的采样点会更少一些因为只取了其中0.7半径范围的点，可以试试直接取bounding box内的整个高斯椭圆，这样点数应该会和centerness差不多。我们之前的实验中也发现高斯半径的范围和分层的参数tau对于结果影响挺大的。另外正如您所说，更少的采样点是有可能加重前背景不均衡的情况。

5）请问您使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels这样的吗，我对齐一下训练试试看。

谢谢。

**Comment by zhuyh1223** [comment]
您好！感谢您的回复。

使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels。数据增强部分仅用了随机翻转 ：h_flip_ratio=0.5, v_flip_ratio=0.5

gghl高斯分配策略中的超参与dataset_obb_pro.py中一致：
IOU_thresh= 0.25
thresh_gh = 0.05

另外，想问一下您单独使用ORC的表征方式的话会对实验结果有多大提升呢？因为之前在ATSS论文中看到regression采用retina或fcos的表征方式几乎对实验结果没多大影响。想请教您，采用ORC的主要提升是来自哪些方面呢？

**Comment by Shank2358** [comment]
> 您好！感谢您的回复。
> 
> 使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels。数据增强部分仅用了随机翻转 ：h_flip_ratio=0.5, v_flip_ratio=0.5
> 
> gghl高斯分配策略中的超参与dataset_obb_pro.py中一致： IOU_thresh= 0.25 thresh_gh = 0.05
> 
> 另外，想问一下您单独使用ORC的表征方式的话会对实验结果有多大提升呢？因为之前在ATSS论文中看到regression采用retina或fcos的表征方式几乎对实验结果没多大影响。想请教您，采用ORC的主要提升是来自哪些方面呢？

谢谢。
1）我把分层也改成了FCOS那样的max(ltbr)来分配，也就是分到stride=16,32的层，我现在跑一下康康，分配长这样。
![image](https://user-images.githubusercontent.com/33946139/156696896-7249ba6d-ed5c-40be-9e5e-a88d0830c564.png)

2）单独ORC回归基本上不差多少，0.5以内的正常波动，回归方式我的实验情况来看更多影响的是收敛速度的快慢，ORC的提升主要是那个预处理的近似，也就是论文table5那里，然后这部分的涨点还有就是OWAM的权重。

3）我把高斯半径调成整个OBB范围试了一下（也就是采样点变多，还是整个目标分到同一层），分层是[0，64，192，inf]分成三层，我的图像裁剪块是800*800pixels（我一会儿会试一下1024的），overlap200，我开了随机裁剪和翻转的增强，还有HSV，结果是这样的
![image](https://user-images.githubusercontent.com/33946139/156698061-31833564-befb-4885-960a-b5e9891a0885.png)
我一会儿对齐您的方案试一下康康
谢谢

**Comment by Shank2358** [comment]
> 您好！感谢您的回复。
> 
> 使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels。数据增强部分仅用了随机翻转 ：h_flip_ratio=0.5, v_flip_ratio=0.5
> 
> gghl高斯分配策略中的超参与dataset_obb_pro.py中一致： IOU_thresh= 0.25 thresh_gh = 0.05
> 
> 另外，想问一下您单独使用ORC的表征方式的话会对实验结果有多大提升呢？因为之前在ATSS论文中看到regression采用retina或fcos的表征方式几乎对实验结果没多大影响。想请教您，采用ORC的主要提升是来自哪些方面呢？

谢谢。
1）我把分层也改成了FCOS那样的max(ltbr)来分配，也就是分到stride=16,32的层，我现在跑一下康康，分配长这样。
![image](https://user-images.githubusercontent.com/33946139/156696896-7249ba6d-ed5c-40be-9e5e-a88d0830c564.png)

2）单独ORC回归基本上不差多少，0.5以内的正常波动，回归方式我的实验情况来看更多影响的是收敛速度的快慢，ORC的提升主要是那个预处理的近似，也就是论文table5那里，然后这部分的涨点还有就是OWAM的权重。

3）我把高斯半径调成整个OBB范围试了一下（也就是采样点变多，还是整个目标分到同一层），分层是[0，64，192，inf]分成三层，我的图像裁剪块是800*800pixels（我一会儿会试一下1024的），overlap200，我开了随机裁剪和翻转的增强，还有HSV，结果是这样的
![image](https://user-images.githubusercontent.com/33946139/156698061-31833564-befb-4885-960a-b5e9891a0885.png)
我一会儿对齐您的方案试一下康康
谢谢

**Comment by Shank2358** [comment]
> 您好！感谢您的回复。
> 
> 使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels。数据增强部分仅用了随机翻转 ：h_flip_ratio=0.5, v_flip_ratio=0.5
> 
> gghl高斯分配策略中的超参与dataset_obb_pro.py中一致： IOU_thresh= 0.25 thresh_gh = 0.05
> 
> 另外，想问一下您单独使用ORC的表征方式的话会对实验结果有多大提升呢？因为之前在ATSS论文中看到regression采用retina或fcos的表征方式几乎对实验结果没多大影响。想请教您，采用ORC的主要提升是来自哪些方面呢？

谢谢。
1）我把分层也改成了FCOS那样的max(ltbr)来分配，也就是分到stride=16,32的层，我现在跑一下康康，分配长这样。
![image](https://user-images.githubusercontent.com/33946139/156696896-7249ba6d-ed5c-40be-9e5e-a88d0830c564.png)

2）单独ORC回归基本上不差多少，0.5以内的正常波动，回归方式我的实验情况来看更多影响的是收敛速度的快慢，ORC的提升主要是那个预处理的近似，也就是论文table5那里，然后这部分的涨点还有就是OWAM的权重。

3）我把高斯半径调成整个OBB范围试了一下（也就是采样点变多，还是整个目标分到同一层），分层是[0，64，192，inf]分成三层，我的图像裁剪块是800*800pixels（我一会儿会试一下1024的），overlap200，我开了随机裁剪和翻转的增强，还有HSV，结果是这样的
![image](https://user-images.githubusercontent.com/33946139/156698061-31833564-befb-4885-960a-b5e9891a0885.png)
我一会儿对齐您的方案试一下康康
谢谢

**Comment by Shank2358** [comment]
> 您好！感谢您的回复。
> 
> 使用的图像是单个尺度的，patch size=1024*1024, overlap=200 pixels。数据增强部分仅用了随机翻转 ：h_flip_ratio=0.5, v_flip_ratio=0.5
> 
> gghl高斯分配策略中的超参与dataset_obb_pro.py中一致： IOU_thresh= 0.25 thresh_gh = 0.05
> 
> 另外，想问一下您单独使用ORC的表征方式的话会对实验结果有多大提升呢？因为之前在ATSS论文中看到regression采用retina或fcos的表征方式几乎对实验结果没多大影响。想请教您，采用ORC的主要提升是来自哪些方面呢？

谢谢。
1）我把分层也改成了FCOS那样的max(ltbr)来分配，也就是分到stride=16,32的层，我现在跑一下康康，分配长这样。
![image](https://user-images.githubusercontent.com/33946139/156696896-7249ba6d-ed5c-40be-9e5e-a88d0830c564.png)

2）单独ORC回归基本上不差多少，0.5以内的正常波动，回归方式我的实验情况来看更多影响的是收敛速度的快慢，ORC的提升主要是那个预处理的近似，也就是论文table5那里，然后这部分的涨点还有就是OWAM的权重。

3）我把高斯半径调成整个OBB范围试了一下（也就是采样点变多，还是整个目标分到同一层），分层是[0，64，192，inf]分成三层，我的图像裁剪块是800*800pixels（我一会儿会试一下1024的），overlap200，我开了随机裁剪和翻转的增强，还有HSV，结果是这样的
![image](https://user-images.githubusercontent.com/33946139/156698061-31833564-befb-4885-960a-b5e9891a0885.png)
我一会儿对齐您的方案试一下康康
谢谢

**Comment by zhuyh1223** [comment]
嗯嗯，明白啦，谢谢您耐心的回复！

**Comment by Shank2358** [comment]
> 嗯嗯，明白啦，谢谢您耐心的回复！

不客气呀~~
这个是Centerness分配的结果，我用的三层FPN就是这个仓库的代码，stride=8,16,32
![image](https://user-images.githubusercontent.com/33946139/156776546-f019e9cb-06f8-4a49-ac1c-45a4cba1f43c.png)
高斯的两组正在跑，整个OBB区域算高斯然后按FCOSmax(ltbr)分层的跑完了，我周末测试一下，今天的DOTA测试次数用完了，有结果了我随时回复您。谢谢。

**Comment by Shank2358** [comment]
> 嗯嗯，明白啦，谢谢您耐心的回复！

这是1024×1024的数据，增强只开了水平和竖直翻转以及随机尺度缩放，stride=8,16,32三层，用的GGHL框架。
分配方式用了高斯椭圆*0.7（这里的高斯我用了论文Algorith1的完整版算法），gh_thresh=0.05，采用了centerness的max(ltbr)分层策略，分层的阈值改成了[0,64,128,inf]，相比于centerness是涨点的
![image](https://user-images.githubusercontent.com/33946139/156873050-43d128dc-e056-411f-b425-e367d01512d4.png)
新的标签分配代码我传上去了，叫datasets_new.py，然后训练日志我会放到log文件夹里面，36个epoch。

这样看来max(ltbr)分层策略确实有效果，然后GGHL高斯这边直接挪到FCOS上效果不好可能是分层分配的原因，一方面原来的GGHL是只有三层然后分层是和高斯半径通过0.3的IOU阈值绑定的，这样看在别的模型上似乎通用性不好，更适合原来的GGHL模型；另一方面确实max(ltbr)这样把目标不同正样本点分配到不同层效果会比整个目标分到同一层好，我的推测是因为max(ltbr)之后每一层回归ltbr的范围更适合于各层感受野，也更均衡，避免了出现某层回归一个比较极端的ltbr值的情况。当然，这个推测还需要更多的实验去证明，我接下来也会根据这两天咱们讨论的情况补充做一些实验。也欢迎您和我讨论交流。

非常感谢您的反馈和意见，让我学到了很多，也期待今后咱们能有机会合作。

谢谢。

**Comment by zhuyh1223** [comment]
> > 嗯嗯，明白啦，谢谢您耐心的回复！
> 
> 这是1024×1024的数据，增强只开了水平和竖直翻转以及随机尺度缩放，stride=8,16,32三层，用的GGHL框架。 分配方式用了高斯椭圆*0.7（这里的高斯我用了论文Algorith1的完整版算法），gh_thresh=0.05，采用了centerness的max(ltbr)分层策略，分层的阈值改成了[0,64,128,inf]，相比于centerness是涨点的 ![image](https://user-images.githubusercontent.com/33946139/156873050-43d128dc-e056-411f-b425-e367d01512d4.png) 新的标签分配代码我传上去了，叫datasets_new.py，然后训练日志我会放到log文件夹里面，36个epoch。
> 
> 这样看来max(ltbr)分层策略确实有效果，然后GGHL高斯这边直接挪到FCOS上效果不好可能是分层分配的原因，一方面原来的GGHL是只有三层然后分层是和高斯半径通过0.3的IOU阈值绑定的，这样看在别的模型上似乎通用性不好，更适合原来的GGHL模型；另一方面确实max(ltbr)这样把目标不同正样本点分配到不同层效果会比整个目标分到同一层好，我的推测是因为max(ltbr)之后每一层回归ltbr的范围更适合于各层感受野，也更均衡，避免了出现某层回归一个比较极端的ltbr值的情况。当然，这个推测还需要更多的实验去证明，我接下来也会根据这两天咱们讨论的情况补充做一些实验。也欢迎您和我讨论交流。
> 
> 非常感谢您的反馈和意见，让我学到了很多，也期待今后咱们能有机会合作。
> 
> 谢谢。

感谢您能这么细致的回复我的问题。我之后也会根据您这边的实验设置重新做一下实验。跟您的讨论也让我受益匪浅，非常感谢！
